//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syncfusion.Windows.Controls.Grid.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Syncfusion_Grid_Wpf {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Syncfusion_Grid_Wpf() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Syncfusion.Windows.Controls.Grid.Resources.Syncfusion.Grid.Wpf", typeof(Syncfusion_Grid_Wpf).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above Average.
        /// </summary>
        internal static string AboveAverage {
            get {
                return ResourceManager.GetString("AboveAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        internal static string AdvanceFilteringContainsString {
            get {
                return ResourceManager.GetString("AdvanceFilteringContainsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equals.
        /// </summary>
        internal static string AdvanceFilteringEqualsString {
            get {
                return ResourceManager.GetString("AdvanceFilteringEqualsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GreaterThan.
        /// </summary>
        internal static string AdvanceFilteringGreaterThanString {
            get {
                return ResourceManager.GetString("AdvanceFilteringGreaterThanString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Between.
        /// </summary>
        internal static string AdvnaceFilteringBetweenString {
            get {
                return ResourceManager.GetString("AdvnaceFilteringBetweenString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After....
        /// </summary>
        internal static string After {
            get {
                return ResourceManager.GetString("After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (All).
        /// </summary>
        internal static string AllFilter {
            get {
                return ResourceManager.GetString("AllFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Drag.
        /// </summary>
        internal static string AllowDrag {
            get {
                return ResourceManager.GetString("AllowDrag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Filter.
        /// </summary>
        internal static string AllowFilter {
            get {
                return ResourceManager.GetString("AllowFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Group.
        /// </summary>
        internal static string AllowGroup {
            get {
                return ResourceManager.GetString("AllowGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Resize.
        /// </summary>
        internal static string AllowResize {
            get {
                return ResourceManager.GetString("AllowResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Sort.
        /// </summary>
        internal static string AllowSort {
            get {
                return ResourceManager.GetString("AllowSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        internal static string AND {
            get {
                return ResourceManager.GetString("AND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Width Settings.
        /// </summary>
        internal static string ApplyWidthSettings {
            get {
                return ResourceManager.GetString("ApplyWidthSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string AutoEllipsisString {
            get {
                return ResourceManager.GetString("AutoEllipsisString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Fit.
        /// </summary>
        internal static string AutoFit {
            get {
                return ResourceManager.GetString("AutoFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1}.
        /// </summary>
        internal static string AutomationPeerName_TotalPageCountKnown {
            get {
                return ResourceManager.GetString("AutomationPeerName_TotalPageCountKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0}.
        /// </summary>
        internal static string AutomationPeerName_TotalPageCountUnknown {
            get {
                return ResourceManager.GetString("AutomationPeerName_TotalPageCountUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before....
        /// </summary>
        internal static string Before {
            get {
                return ResourceManager.GetString("Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to begins with.
        /// </summary>
        internal static string BeginsWith {
            get {
                return ResourceManager.GetString("BeginsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begins With....
        /// </summary>
        internal static string BeginsWithCaps {
            get {
                return ResourceManager.GetString("BeginsWithCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below Average.
        /// </summary>
        internal static string BelowAverage {
            get {
                return ResourceManager.GetString("BelowAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Between....
        /// </summary>
        internal static string Between {
            get {
                return ResourceManager.GetString("Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Blanks).
        /// </summary>
        internal static string BlankFilterText {
            get {
                return ResourceManager.GetString("BlankFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The underlying data source cannot perform sort.
        /// </summary>
        internal static string CanntPerformSortMessage {
            get {
                return ResourceManager.GetString("CanntPerformSortMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Filter.
        /// </summary>
        internal static string ClearFilter {
            get {
                return ResourceManager.GetString("ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard CopyPaste.
        /// </summary>
        internal static string ClipboardCopyPaste {
            get {
                return ResourceManager.GetString("ClipboardCopyPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColumnFormat.
        /// </summary>
        internal static string ColumnFormat {
            get {
                return ResourceManager.GetString("ColumnFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Covered Range {0}.
        /// </summary>
        internal static string CommandAddCoveredRanges {
            get {
                return ResourceManager.GetString("CommandAddCoveredRanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Cells {0}.
        /// </summary>
        internal static string CommandChangeCells {
            get {
                return ResourceManager.GetString("CommandChangeCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Width {0} to {1}.
        /// </summary>
        internal static string CommandColumnWidth {
            get {
                return ResourceManager.GetString("CommandColumnWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change CurrentCell Value Row {0} Column {1}.
        /// </summary>
        internal static string CommandCurrentCellValue {
            get {
                return ResourceManager.GetString("CommandCurrentCellValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Default Column Width {0}.
        /// </summary>
        internal static string CommandDefaultColumnSize {
            get {
                return ResourceManager.GetString("CommandDefaultColumnSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Default Row Height to {0}.
        /// </summary>
        internal static string CommandDefaultRowSize {
            get {
                return ResourceManager.GetString("CommandDefaultRowSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Footer Columms.
        /// </summary>
        internal static string CommandFooterColumnsCount {
            get {
                return ResourceManager.GetString("CommandFooterColumnsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Footer Rows.
        /// </summary>
        internal static string CommandFooterRowsCount {
            get {
                return ResourceManager.GetString("CommandFooterRowsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Frozen Columns.
        /// </summary>
        internal static string CommandFrozenColumnsCount {
            get {
                return ResourceManager.GetString("CommandFrozenColumnsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Frozen Rows.
        /// </summary>
        internal static string CommandFrozenRowsCount {
            get {
                return ResourceManager.GetString("CommandFrozenRowsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Header Columms.
        /// </summary>
        internal static string CommandHeaderColumnsCount {
            get {
                return ResourceManager.GetString("CommandHeaderColumnsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Header Rows.
        /// </summary>
        internal static string CommandHeaderRowsCount {
            get {
                return ResourceManager.GetString("CommandHeaderRowsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert {0} columns at column {1}.
        /// </summary>
        internal static string CommandInsertColumns {
            get {
                return ResourceManager.GetString("CommandInsertColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert {0} rows at row {1}.
        /// </summary>
        internal static string CommandInsertRows {
            get {
                return ResourceManager.GetString("CommandInsertRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move {1} column from {0} to {2}.
        /// </summary>
        internal static string CommandMoveColumns {
            get {
                return ResourceManager.GetString("CommandMoveColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move {1} rows from {0} to {2}.
        /// </summary>
        internal static string CommandMoveRows {
            get {
                return ResourceManager.GetString("CommandMoveRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Column {0} to {1}.
        /// </summary>
        internal static string CommandRemoveColumns {
            get {
                return ResourceManager.GetString("CommandRemoveColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Covered Range {0}.
        /// </summary>
        internal static string CommandRemoveCoveredRanges {
            get {
                return ResourceManager.GetString("CommandRemoveCoveredRanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Row {0} to {1}.
        /// </summary>
        internal static string CommandRemoveRows {
            get {
                return ResourceManager.GetString("CommandRemoveRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Height {0} to {1}.
        /// </summary>
        internal static string CommandRowHeight {
            get {
                return ResourceManager.GetString("CommandRowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Selection State Row {0} Column {1}.
        /// </summary>
        internal static string CommandSelectionState {
            get {
                return ResourceManager.GetString("CommandSelectionState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm delete.
        /// </summary>
        internal static string ConfirmDeleteMessage {
            get {
                return ResourceManager.GetString("ConfirmDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains....
        /// </summary>
        internal static string Contains {
            get {
                return ResourceManager.GetString("Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contains.
        /// </summary>
        internal static string ContainsSmall {
            get {
                return ResourceManager.GetString("ContainsSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string CurrentPagePrefix_TotalPageCountKnown {
            get {
                return ResourceManager.GetString("CurrentPagePrefix_TotalPageCountKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string CurrentPagePrefix_TotalPageCountUnknown {
            get {
                return ResourceManager.GetString("CurrentPagePrefix_TotalPageCountUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of {0}.
        /// </summary>
        internal static string CurrentPageSuffix_TotalPageCountKnown {
            get {
                return ResourceManager.GetString("CurrentPageSuffix_TotalPageCountKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CurrentPageSuffix_TotalPageCountUnknown {
            get {
                return ResourceManager.GetString("CurrentPageSuffix_TotalPageCountUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1}.
        /// </summary>
        internal static string CurrentPageText {
            get {
                return ResourceManager.GetString("CurrentPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom AutoFilter.
        /// </summary>
        internal static string CustomAutoFilter {
            get {
                return ResourceManager.GetString("CustomAutoFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Filters.
        /// </summary>
        internal static string DateFilters {
            get {
                return ResourceManager.GetString("DateFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Oldest to Newest.
        /// </summary>
        internal static string DateTimeAscending {
            get {
                return ResourceManager.GetString("DateTimeAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Newest to Oldest.
        /// </summary>
        internal static string DateTimeDescending {
            get {
                return ResourceManager.GetString("DateTimeDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove the selected record(s)?.
        /// </summary>
        internal static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description  Change Cells.
        /// </summary>
        internal static string DescriptionChangeCells {
            get {
                return ResourceManager.GetString("DescriptionChangeCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does not begins with.
        /// </summary>
        internal static string DoesNotBeginsWith {
            get {
                return ResourceManager.GetString("DoesNotBeginsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does not contain.
        /// </summary>
        internal static string DoesNotContain {
            get {
                return ResourceManager.GetString("DoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does Not Contain.
        /// </summary>
        internal static string DoesNotContainCaps {
            get {
                return ResourceManager.GetString("DoesNotContainCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does not end with.
        /// </summary>
        internal static string DoesNotEndWith {
            get {
                return ResourceManager.GetString("DoesNotEndWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does Not Equal....
        /// </summary>
        internal static string DoesNotEqual {
            get {
                return ResourceManager.GetString("DoesNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does not equal.
        /// </summary>
        internal static string DoesNotEquals {
            get {
                return ResourceManager.GetString("DoesNotEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop columns here.
        /// </summary>
        internal static string DragDropText {
            get {
                return ResourceManager.GetString("DragDropText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic Options:.
        /// </summary>
        internal static string DynamicOptions {
            get {
                return ResourceManager.GetString("DynamicOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndsWith.
        /// </summary>
        internal static string EndsWith {
            get {
                return ResourceManager.GetString("EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends With....
        /// </summary>
        internal static string EndsWithCaps {
            get {
                return ResourceManager.GetString("EndsWithCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ends with.
        /// </summary>
        internal static string EndsWithSmall {
            get {
                return ResourceManager.GetString("EndsWithSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Filter Value...
        /// </summary>
        internal static string EnterFilterValue {
            get {
                return ResourceManager.GetString("EnterFilterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to equals.
        /// </summary>
        internal static string EqualsSmall {
            get {
                return ResourceManager.GetString("EqualsSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equals....
        /// </summary>
        internal static string EqualsString {
            get {
                return ResourceManager.GetString("EqualsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Date To...
        /// </summary>
        internal static string FilterDateTo {
            get {
                return ResourceManager.GetString("FilterDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GreaterThan....
        /// </summary>
        internal static string GreaterThan {
            get {
                return ResourceManager.GetString("GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GreaterThanOrEqual.
        /// </summary>
        internal static string GreaterThanOrEqual {
            get {
                return ResourceManager.GetString("GreaterThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater Than Or Equal To....
        /// </summary>
        internal static string GreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("GreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string HCenter {
            get {
                return ResourceManager.GetString("HCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Text:.
        /// </summary>
        internal static string HeaderText {
            get {
                return ResourceManager.GetString("HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string HLeft {
            get {
                return ResourceManager.GetString("HLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        internal static string Horizontal {
            get {
                return ResourceManager.GetString("Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string HRight {
            get {
                return ResourceManager.GetString("HRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch.
        /// </summary>
        internal static string HStretch {
            get {
                return ResourceManager.GetString("HStretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NumericButtonPanel contains invalid children..
        /// </summary>
        internal static string InvalidButtonPanelContent {
            get {
                return ResourceManager.GetString("InvalidButtonPanelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Column added.
        /// </summary>
        internal static string InvalidColumn {
            get {
                return ResourceManager.GetString("InvalidColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DataTime.
        /// </summary>
        internal static string InvalidDataTime {
            get {
                return ResourceManager.GetString("InvalidDataTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Data Filter.
        /// </summary>
        internal static string InvalidDataToFilter {
            get {
                return ResourceManager.GetString("InvalidDataToFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} time span must be strictly positive..
        /// </summary>
        internal static string InvalidTimeSpan {
            get {
                return ResourceManager.GetString("InvalidTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is after.
        /// </summary>
        internal static string isafter {
            get {
                return ResourceManager.GetString("isafter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is after or equal to.
        /// </summary>
        internal static string isafterorequalto {
            get {
                return ResourceManager.GetString("isafterorequalto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is before.
        /// </summary>
        internal static string isbefore {
            get {
                return ResourceManager.GetString("isbefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is before or equal to.
        /// </summary>
        internal static string isbeforeorequalto {
            get {
                return ResourceManager.GetString("isbeforeorequalto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is greater than.
        /// </summary>
        internal static string IsGreaterThan {
            get {
                return ResourceManager.GetString("IsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is greater than or equal to.
        /// </summary>
        internal static string IsGreaterThanOrEqualto {
            get {
                return ResourceManager.GetString("IsGreaterThanOrEqualto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is less than.
        /// </summary>
        internal static string IsLessThan {
            get {
                return ResourceManager.GetString("IsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is less than or equl to.
        /// </summary>
        internal static string IsLessThanorEqualto {
            get {
                return ResourceManager.GetString("IsLessThanorEqualto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is ReadOnly.
        /// </summary>
        internal static string IsReadOnly {
            get {
                return ResourceManager.GetString("IsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Month.
        /// </summary>
        internal static string LastMonth {
            get {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Week.
        /// </summary>
        internal static string LastWeek {
            get {
                return ResourceManager.GetString("LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Year.
        /// </summary>
        internal static string LastYear {
            get {
                return ResourceManager.GetString("LastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LessThan.
        /// </summary>
        internal static string LessThan {
            get {
                return ResourceManager.GetString("LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LessThanOrEqual.
        /// </summary>
        internal static string LessThanOrEqual {
            get {
                return ResourceManager.GetString("LessThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less Than Or Equal To....
        /// </summary>
        internal static string LessThanOrEqualTo {
            get {
                return ResourceManager.GetString("LessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less Than....
        /// </summary>
        internal static string LessThanWithSpace {
            get {
                return ResourceManager.GetString("LessThanWithSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Case.
        /// </summary>
        internal static string MatchCase {
            get {
                return ResourceManager.GetString("MatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Month.
        /// </summary>
        internal static string NextMonth {
            get {
                return ResourceManager.GetString("NextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Week.
        /// </summary>
        internal static string NextWeek {
            get {
                return ResourceManager.GetString("NextWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Year.
        /// </summary>
        internal static string NextYear {
            get {
                return ResourceManager.GetString("NextYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items match your search..
        /// </summary>
        internal static string NoItemMatch {
            get {
                return ResourceManager.GetString("NoItemMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no more items to remove or it is not supported in the underlying data source.
        /// </summary>
        internal static string NoMoreItemRemoveMessage {
            get {
                return ResourceManager.GetString("NoMoreItemRemoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Records found.
        /// </summary>
        internal static string NoRecordsfound {
            get {
                return ResourceManager.GetString("NoRecordsfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough space, Do you wish to Continue?.
        /// </summary>
        internal static string NotEnoughSpaceMessage {
            get {
                return ResourceManager.GetString("NotEnoughSpaceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotEquals.
        /// </summary>
        internal static string NotEquals {
            get {
                return ResourceManager.GetString("NotEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underlying data source does not supports deleting items, Try binding an IList source.
        /// </summary>
        internal static string NotSupportDeletingItemMessage {
            get {
                return ResourceManager.GetString("NotSupportDeletingItemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Smallest to Largest.
        /// </summary>
        internal static string NumberAscending {
            get {
                return ResourceManager.GetString("NumberAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Largest to Smallest.
        /// </summary>
        internal static string NumberDescending {
            get {
                return ResourceManager.GetString("NumberDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Filters.
        /// </summary>
        internal static string NumberFilters {
            get {
                return ResourceManager.GetString("NumberFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        internal static string OR {
            get {
                return ResourceManager.GetString("OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PageIndex property can only be set to -1 when the Source property is null or the PageSize property is 0..
        /// </summary>
        internal static string PageIndexMustBeNegativeOne {
            get {
                return ResourceManager.GetString("PageIndexMustBeNegativeOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Sizes.
        /// </summary>
        internal static string PageSizes {
            get {
                return ResourceManager.GetString("PageSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Output Color.
        /// </summary>
        internal static string PrintOutputColor {
            get {
                return ResourceManager.GetString("PrintOutputColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string PrintText {
            get {
                return ResourceManager.GetString("PrintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string PrintZoom {
            get {
                return ResourceManager.GetString("PrintZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectAll.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Select All).
        /// </summary>
        internal static string SelectAllFilter {
            get {
                return ResourceManager.GetString("SelectAllFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Filter Date...
        /// </summary>
        internal static string SelectFilterDate {
            get {
                return ResourceManager.GetString("SelectFilterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetFrozenColumn.
        /// </summary>
        internal static string SetFrozenColumn {
            get {
                return ResourceManager.GetString("SetFrozenColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Column Options.
        /// </summary>
        internal static string ShowColumnOptionsFilter {
            get {
                return ResourceManager.GetString("ShowColumnOptionsFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show rows where :.
        /// </summary>
        internal static string ShowRowsWhere {
            get {
                return ResourceManager.GetString("ShowRowsWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide To Filter...
        /// </summary>
        internal static string SlideToFilter {
            get {
                return ResourceManager.GetString("SlideToFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartsWith.
        /// </summary>
        internal static string StartsWith {
            get {
                return ResourceManager.GetString("StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort A to Z.
        /// </summary>
        internal static string StringAscending {
            get {
                return ResourceManager.GetString("StringAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Z to A.
        /// </summary>
        internal static string StringDescending {
            get {
                return ResourceManager.GetString("StringDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Alignment:.
        /// </summary>
        internal static string TextAlignment {
            get {
                return ResourceManager.GetString("TextAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Filters.
        /// </summary>
        internal static string TextFilters {
            get {
                return ResourceManager.GetString("TextFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Month.
        /// </summary>
        internal static string ThisMonth {
            get {
                return ResourceManager.GetString("ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Week.
        /// </summary>
        internal static string ThisWeek {
            get {
                return ResourceManager.GetString("ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Year.
        /// </summary>
        internal static string ThisYear {
            get {
                return ResourceManager.GetString("ThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        internal static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 10.
        /// </summary>
        internal static string Top10 {
            get {
                return ResourceManager.GetString("Top10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be set because the underlying property is read only..
        /// </summary>
        internal static string UnderlyingPropertyIsReadOnly {
            get {
                return ResourceManager.GetString("UnderlyingPropertyIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use * to represent any series of characters.
        /// </summary>
        internal static string UseSeriesCharacter {
            get {
                return ResourceManager.GetString("UseSeriesCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ? to represent any single character.
        /// </summary>
        internal static string UseSingleCharacter {
            get {
                return ResourceManager.GetString("UseSingleCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than or equal to {1}..
        /// </summary>
        internal static string ValueMustBeGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("ValueMustBeGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        internal static string VBottom {
            get {
                return ResourceManager.GetString("VBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string VCenter {
            get {
                return ResourceManager.GetString("VCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        internal static string Vertical {
            get {
                return ResourceManager.GetString("Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch.
        /// </summary>
        internal static string VStretch {
            get {
                return ResourceManager.GetString("VStretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        internal static string VTop {
            get {
                return ResourceManager.GetString("VTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width Options.
        /// </summary>
        internal static string WidthOptions {
            get {
                return ResourceManager.GetString("WidthOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        internal static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
